apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-http-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-http-server
  template:
    metadata:
      labels:
        app: simple-http-server
    spec:
      containers:
      - name: simple-http-server
        image: dinhtranvan/simple-http-server:1149cb9a2c2102e2566819fd13bac05bb1e6a417
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: secret-volume
          mountPath: /etc/secret-volume
          readOnly: true

      volumes:
      - name: secret-volume
        secret:
          secretName: secret