name: Deploy to Kubernetes

on:
  push:
    # Only run when tag version is pushed. For example: v1.0.0
    tags:
      - 'v*'
    # Ignore changes in non-application files.
    paths-ignore:
      - 'k8s/*'
      - 'terraform/*'
      - '**/README.md'
      - 'images/*'

jobs:
  # Build/push docker image then trigger argocd
  ci-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: dinhtranvan/simple-http-server:${{ github.ref }}

    - name: Update new image version for deployment.
      run: |
        sed -i 's/dinhtranvan\/simple-http-server:[a-f0-9]\{40\}/dinhtranvan\/simple-http-server:${{ github.ref }}/g' k8s/deployment.yaml
        cat k8s/deployment.yaml

      # After push, argocd will detect the change and deploy new version of the application on k8s.
    - name: Commit change to trigger Argocd
      uses: EndBug/add-and-commit@v9
      with:
        committer_name: GitHub Actions
        committer_email: actions@github.com
        message: Deploy new image version ${{ github.sha }}.